import type { SitePage } from "./site";

export const examplePages: SitePage[] = [
  {
    slug: ["examples"],
    kind: "hub",
    title: "InstaDoodle Examples",
    description: "InstaDoodle examples for marketing, business owners, content creators, and nonprofits—plus a practical framework for planning a whiteboard animation that teaches one clear idea.",
    h1: "InstaDoodle examples that show how a message becomes a video",
    eyebrow: "Examples hub",
    primaryKeyword: "InstaDoodle examples",
    intro: "These official InstaDoodle examples are most useful when you watch for the communication job behind them: the audience question, the sequence of scenes, and the single action each video asks a viewer to take.",
    heroCtas: [
      { href: "#watch", label: "Watch the workflow demo" },
      { href: "/examples/marketing", label: "Explore marketing examples" },
    ],
    blocks: [
      {
        type: "prose",
        heading: "Use examples to study structure, not to copy a script",
        body: [
          "A strong whiteboard animation example makes one promise to the viewer: by the end, a question will feel easier to answer. The drawing style can make that explanation pleasant to watch, but it is the order of the ideas that carries the result. Start by identifying the question each video answers before you study the artwork or motion.",
          "Look for the first scene. Does it name a practical problem, create a contrast, or introduce an unfamiliar idea? Then watch how the middle scenes narrow the explanation. Useful examples avoid asking a single frame to explain everything; a character, a label, and one relationship are often enough for a viewer to keep moving with the story.",
          "Finally, examine the ending. A good example does not suddenly introduce a new claim or a pile of features. It summarizes the point and offers a sensible next step. Borrow that discipline for your own topic, whether you are creating a whiteboard marketing video, a customer explanation, or a mission-focused update.",
        ],
      },
      {
        type: "vimeo",
        anchor: "watch",
        heading: "Start with the product workflow",
        intro: "The official demo is a useful orientation before you choose an audience-specific example. Watch it with a draft topic in mind, then note the few scenes your own explanation would need.",
        video: "demo",
        ctaHref: "/whiteboard-animation-software",
        ctaLabel: "Read the workflow guide",
      },
      {
        type: "cards",
        heading: "Choose the example closest to your communication job",
        intro: "Each guide below interprets a supplied official sample through the planning decisions that matter before you open an editor.",
        items: [
          { title: "Marketing examples", body: "Turn a customer tension into a concise explainer: establish the problem, make the value legible, and direct attention to one next step.", href: "/examples/marketing" },
          { title: "Business-owner examples", body: "Explain an offer, a customer process, or a service principle without turning a useful video into a feature inventory.", href: "/examples/business-owners" },
          { title: "Content-creator examples", body: "Build a repeatable idea-to-script-to-scene workflow that respects audience attention and gives one concept room to land.", href: "/examples/content-creators" },
          { title: "Nonprofit examples", body: "Connect a mission to a concrete human problem, a program, and a clear supporter action without overstating outcomes.", href: "/examples/nonprofits" },
        ],
      },
      {
        type: "steps",
        heading: "A practical way to review any doodle-video example",
        intro: "Use this short review before borrowing the shape of an example for a new subject.",
        items: [
          { title: "Name the viewer question", body: "Write the question the audience has before the first scene. This keeps the video focused on a viewer need instead of a list of things you want to say." },
          { title: "Map one idea per scene", body: "List the job of every scene in plain language. If two scenes do the same job, combine them; if one has three jobs, split it." },
          { title: "Check the final action", body: "Make the ending a natural consequence of the explanation. A viewer should know what to do next without being pressured or surprised." },
        ],
      },
      {
        type: "prose",
        heading: "Match the format to the audience, not the trend",
        body: [
          "Marketing teams often need a short problem-to-benefit narrative. A business owner may need to make an unfamiliar service easier to understand. A creator may need an opening that earns the next thirty seconds, while a nonprofit may need to explain why a specific action matters. Those jobs can all use a doodle-video format, but they should not use the same script.",
          "That is why this hub is organized by audience rather than by a generic gallery. The spokes give you a planning lens, an official video, and related guides for the next decision. Use them to create an original explanation grounded in your own audience, evidence, and offer—not a lookalike of someone else’s message.",
        ],
      },
      {
        type: "faq",
        heading: "Examples hub questions.",
        items: [
          ["What should I look for in an InstaDoodle example?", "Start with message structure: the viewer question, the order of scenes, the narration-to-visual match, and the final action. Style matters after those fundamentals are clear."],
          ["Can one whiteboard video work for more than one audience?", "A core explanation can be reused, but the opening problem, vocabulary, examples, and final action should change for each audience. Reformatting alone is not audience strategy."],
          ["Are these customer case studies?", "No. These are editorial planning guides built around official product videos supplied for this site. They do not claim customer outcomes, reviews, or results."],
        ],
      },
      { type: "callout", kind: "editorial", body: "The supplied videos show official product examples. The planning advice on this hub is original editorial guidance, not a performance claim or customer case study." },
    ],
    related: ["/features", "/resources", "/whiteboard-animation-examples"],
    cta: {
      eyebrow: "Choose a starting point",
      title: "Build your next explanation around one audience question.",
      body: "Choose an audience guide, map the scene sequence, then compare the workflow and features you would actually use.",
      visualImage: "box",
      visualAlt: "Official InstaDoodle product visual accompanying the examples hub next step",
      primaryHref: "/examples/marketing",
      primaryLabel: "Explore marketing examples",
      secondaryHref: "/features",
      secondaryLabel: "Explore the features",
    },
  },
  {
    slug: ["examples", "marketing"],
    kind: "commercial",
    title: "InstaDoodle Marketing Examples",
    description: "InstaDoodle marketing examples for whiteboard explainers, product narratives, and campaign videos—how to plan the audience problem, scene flow, proof, and next step.",
    h1: "InstaDoodle marketing examples for messages people can follow",
    eyebrow: "Marketing examples",
    primaryKeyword: "InstaDoodle marketing examples",
    intro: "Marketing video works when it helps a specific audience make sense of a problem before asking for attention. This guide uses an official sample to show how a whiteboard explainer can earn that attention through a clear scene sequence.",
    heroCtas: [
      { href: "#official-example", label: "Watch the marketing example" },
      { href: "/examples", label: "Browse all examples" },
    ],
    blocks: [
      {
        type: "prose",
        heading: "Begin with the tension your audience already recognizes",
        body: [
          "The first scene of a marketing explainer should make a viewer feel understood, not simply informed that a product exists. That may be a delay in a familiar workflow, a recurring customer question, or the cost of doing something manually. Name the situation in language your audience would use, then make it visible with a simple visual relationship rather than a dense opening paragraph.",
          "From there, make one promise for the video. It might be that a process can become easier to grasp, that a service removes an avoidable step, or that an offer changes a decision. A clear promise gives the script a filter: every scene should help the viewer understand it, trust it, or act on it. Anything that merely repeats a slogan is a candidate to remove.",
          "Whiteboard marketing videos are especially useful when the product needs explanation before it needs a demonstration. They can introduce a category, clarify a sequence, or make an abstract benefit concrete. If your buyer needs to inspect an interface or a physical material, pair the explainer with the product evidence they need instead of pretending the doodle format can replace it.",
        ],
      },
      {
        type: "vimeo",
        anchor: "official-example",
        heading: "Official marketing example",
        intro: "Use the sample to study the order of the message. Notice how each visual supports the narration instead of competing with it, then outline an original version for your own audience.",
        video: "marketers",
        ctaHref: "/use-cases",
        ctaLabel: "Explore marketing use cases",
      },
      {
        type: "steps",
        heading: "A five-scene marketing explainer outline",
        intro: "This sequence is a planning pattern, not a fixed formula. Keep only the scenes that serve the audience question.",
        items: [
          { title: "Show the current friction", body: "Open with the recognizable situation. Draw one person, process, or obstacle so the problem has a concrete shape without inventing a statistic or dramatic claim." },
          { title: "Clarify what needs to change", body: "Explain the missing capability or better outcome in plain language. This scene connects the problem to the category of solution before you introduce your own offer." },
          { title: "Make the approach visible", body: "Show the simple sequence, comparison, or cause-and-effect relationship that explains how the solution helps. Avoid cramming a feature list into a single scene." },
          { title: "Support the decision", body: "Offer the practical information a viewer needs next: who the approach suits, what they can explore, or what question they should verify. Do not fabricate social proof or results." },
          { title: "Ask for one next step", body: "End with a single action that matches the video: read a guide, view a demo, compare options, or contact an approved channel. A useful CTA continues the research rather than ends it." },
        ],
      },
      {
        type: "cards",
        heading: "Marketing formats that suit a doodle workflow",
        items: [
          { title: "Category explainer", body: "Useful when the audience needs to understand a new concept before evaluating individual products. Define the problem, the model, and the next research question." },
          { title: "Product narrative", body: "Useful when a product has a clear before-and-after workflow. Focus on the sequence of decisions, then link to evidence that supports feature details." },
          { title: "Campaign companion", body: "Useful when a landing page or email needs a short visual summary. Keep the video consistent with the page’s promise and give it one supporting CTA." },
        ],
      },
      {
        type: "prose",
        heading: "Keep persuasion specific and verifiable",
        body: [
          "Marketing credibility grows when a video separates what is verified from what is editorial. Use product documentation for capability statements, use your own approved evidence for claims, and label interpretation as interpretation. If you do not have proof for a benefit, frame it as a question a prospective buyer should explore rather than as a guarantee.",
          "Before you publish, watch the video with the sound off and with the script in front of you. The visual should make the spoken point easier to retain, while captions or a written summary keep the message usable in quiet feeds and accessible contexts. Then make sure the linked page answers the question the final scene creates.",
        ],
      },
      {
        type: "faq",
        heading: "Marketing-example questions.",
        items: [
          ["How long should a whiteboard marketing video be?", "Use the time required to answer one audience question clearly. Cut scenes that repeat the narration; do not stretch a short point into a longer video just to meet a duration target."],
          ["Should a marketing example show every feature?", "No. Select the features that make the specific message credible, then link to a detailed feature guide for viewers who need the full evaluation."],
          ["Can an affiliate marketing video use this structure?", "Yes, if it explains the product accurately, keeps the relationship clear, and links to the official offer through an approved disclosed affiliate CTA rather than hiding the destination."],
        ],
      },
      { type: "callout", kind: "editorial", body: "A marketing example can teach a message structure, but it cannot substantiate an unverified performance claim. Keep evidence, disclosures, and final actions aligned with the offer you actually have." },
    ],
    related: ["/examples", "/features", "/pricing"],
    cta: {
      title: "Turn one audience problem into a focused scene plan.",
      body: "Explore the product workflow, use the planning guides, and verify current offer details before making a buying decision.",
      primaryHref: "/resources",
      primaryLabel: "Open planning resources",
      secondaryHref: "/whiteboard-animation-software",
      secondaryLabel: "See the workflow",
    },
  },
  {
    slug: ["examples", "business-owners"],
    kind: "commercial",
    title: "InstaDoodle Business Video Examples",
    description: "InstaDoodle business video examples for explaining an offer, service process, customer question, or team workflow with clear whiteboard animation scenes.",
    h1: "InstaDoodle business video examples for clearer customer explanations",
    eyebrow: "Business-owner examples",
    primaryKeyword: "InstaDoodle business videos",
    intro: "A business video should reduce uncertainty for a customer, a prospect, or a team member. This guide uses an official example to show how whiteboard animation can make an offer or process easier to follow without turning it into a hard-sell page.",
    heroCtas: [
      { href: "#official-example", label: "Watch the business example" },
      { href: "/examples", label: "Browse all examples" },
    ],
    blocks: [
      {
        type: "prose",
        heading: "Explain the decision before you explain the business",
        body: [
          "Business owners often know their service so well that they start an explainer in the middle of the story. A new customer does not. Start where the viewer is: the question they are trying to answer, the step that feels uncertain, or the consequence of a confusing process. This makes the video useful even before it mentions the company behind it.",
          "Once the problem is visible, use scenes to make the decision path easier to trace. A service business might show what happens before, during, and after an engagement. A local business might show how a customer gets from a need to a completed result. An internal team might show where a request enters a workflow and who owns the next handoff.",
          "The goal is not to compress every policy, package, or exception into a two-minute animation. Give the viewer a reliable mental model, then point them to the approved source for the details that change. This is more useful than a fast feature list and avoids making promises your operating process cannot support.",
        ],
      },
      {
        type: "vimeo",
        anchor: "official-example",
        heading: "Official business-owner example",
        intro: "Watch for how an example moves from a familiar situation to a manageable explanation. Use that transition to draft a customer-first opening for your own business.",
        video: "businessOwners",
        ctaHref: "/whiteboard-video-maker",
        ctaLabel: "Plan a whiteboard video",
      },
      {
        type: "cards",
        heading: "Three business questions worth turning into a video",
        items: [
          { title: "What happens after I enquire?", body: "Show the early customer journey as a sequence: the request, the response, the information needed, and the next confirmed step. Keep legal or pricing details on their approved pages." },
          { title: "How does this service solve my problem?", body: "Translate the service into a visible before-and-after workflow. Explain the mechanism in simple terms, and point to evidence rather than claiming a universal outcome." },
          { title: "How should my team follow this process?", body: "Use scenes for the order people actually work in. A concise visual SOP can support training, provided the written procedure remains the source of record." },
        ],
      },
      {
        type: "steps",
        heading: "Build a customer-first business explainer",
        intro: "Use this sequence to keep a business video practical, truthful, and easy to revisit.",
        items: [
          { title: "Collect real customer questions", body: "Start with questions that arrive in sales calls, support messages, or onboarding—not assumptions about what sounds compelling. Group overlapping questions until one clear video topic emerges." },
          { title: "Write the plain-language answer", body: "Draft the spoken explanation before visuals. Explain the process as if you were helping a customer make a decision, then remove jargon the viewer does not need." },
          { title: "Storyboard the proof points", body: "Assign one visual action to each important line. Link out to verified documentation, a live demo, or an approved policy when a viewer needs more than an illustration." },
          { title: "Review the commitments", body: "Check every claim against the current business process, availability, and terms. A video should never promise a timeline, price, or result the business has not approved." },
        ],
      },
      {
        type: "prose",
        heading: "Use the video to make the rest of your site easier to use",
        body: [
          "A business explainer has more value when it sits in a connected customer journey. Its opening should match the page headline that brought the viewer there. Its middle should link to the guide, FAQ, or process page where details live. Its ending should point to one action the customer can complete with confidence, such as reviewing current options or preparing a request.",
          "That connection also makes updates manageable. If one policy changes, update the linked source and the scene that introduces it instead of leaving several contradictory pages and clips online. A scene-based workflow supports that discipline, but the editorial review is still the important part.",
        ],
      },
      {
        type: "faq",
        heading: "Business-video questions.",
        items: [
          ["What makes a business explainer useful?", "It answers a real customer or team question in the order they need it, uses plain language, and directs them to current approved details rather than replacing them."],
          ["Can a video replace a pricing or policy page?", "No. Video can orient a viewer, but time-sensitive prices, legal terms, and operational details should remain on a maintained, approved source of truth."],
          ["Should a small business use an animated video?", "It can be a practical format when the offer or process needs explanation. Start with a narrow question and a clear script; the size of the business is less important than the clarity of the job."],
        ],
      },
      { type: "callout", kind: "verify", body: "Treat business videos as explanations, not contracts. Verify current pricing, availability, guarantees, licensing, and policy details on the approved source before publishing or linking from a CTA." },
    ],
    related: ["/examples", "/training-video-software", "/whiteboard-animation-examples"],
    cta: {
      title: "Map the question your customers ask most often.",
      body: "Use the planning resources to turn that question into a clear scene sequence, then explore the product workflow.",
      primaryHref: "/resources",
      primaryLabel: "Open planning resources",
      secondaryHref: "/features",
      secondaryLabel: "Explore the features",
    },
  },
  {
    slug: ["examples", "content-creators"],
    kind: "commercial",
    title: "InstaDoodle Content Creator Workflow Examples",
    description: "InstaDoodle content creator workflow examples for turning a hook, script, and storyboard into clear whiteboard-animation videos across channels.",
    h1: "InstaDoodle content creator workflow examples that start with the idea",
    eyebrow: "Content-creator examples",
    primaryKeyword: "InstaDoodle content creator workflow",
    intro: "For a content creator, a doodle video is most valuable when it makes a repeatable editorial workflow easier: a focused hook, a script with one takeaway, a storyboard, and a version that fits the channel where people will see it.",
    heroCtas: [
      { href: "#official-example", label: "Watch the creator example" },
      { href: "/examples", label: "Browse all examples" },
    ],
    blocks: [
      {
        type: "prose",
        heading: "Make the hook a promise you can keep",
        body: [
          "A creator’s opening does not need to be louder than every other video in a feed. It needs to make a clear promise about the question that will be answered. Lead with a problem, a contrast, or a surprising relationship that your script can genuinely unpack. The next scene should immediately prove that the viewer is in the right place.",
          "Whiteboard animation can help creators keep that promise because it gives each spoken beat a visual job. A character can represent a point of view, an arrow can show the next step, and a simple before-and-after can make an abstract idea concrete. The important decision is not which asset looks most interesting; it is which visual helps the audience retain the line they just heard.",
          "A repeatable creator workflow separates the work into stages. Research establishes what is true, the script establishes what matters, the storyboard establishes what viewers will see, and the edit establishes pace. When you skip straight to visuals, the video may look active but still leave the audience unsure what it was about.",
        ],
      },
      {
        type: "vimeo",
        anchor: "official-example",
        heading: "Official content-creator example",
        intro: "Use the sample to notice pacing and scene changes. Then adapt the planning method—not the specific wording or sequence—to an original idea and audience.",
        video: "contentCreators",
        ctaHref: "/resources",
        ctaLabel: "Use the planning resources",
      },
      {
        type: "steps",
        heading: "A reusable creator workflow",
        intro: "Use this workflow for an explainer, a video essay segment, a short tutorial, or a social cutdown.",
        items: [
          { title: "Research one defensible takeaway", body: "Collect the sources and examples you need before writing. Reduce them to one takeaway that can be explained accurately in the time you have." },
          { title: "Write for the ear", body: "Use short sentences, specific verbs, and a natural spoken rhythm. Read the script aloud; if a line is hard to say, it will be hard to follow." },
          { title: "Assign a visual action", body: "Give every beat a purpose: introduce, compare, sequence, or recap. Avoid using on-screen text as a second copy of the entire voiceover." },
          { title: "Adapt for the destination", body: "Plan landscape, vertical, or square framing before the scene is built. Keep captions and safe text placement in view for sound-off and mobile contexts." },
          { title: "Create the next path", body: "Choose one relevant next link for viewers who want more: a deeper guide, a related example, or a source page. A useful internal link continues the topic instead of diverting attention." },
        ],
      },
      {
        type: "cards",
        heading: "Formats creators can adapt",
        items: [
          { title: "Explainer series", body: "Use a repeating question → model → recap structure so viewers learn what to expect while each topic remains original." },
          { title: "Tutorial companion", body: "Use the doodle video to introduce the why and sequence, then pair it with a screen recording or written steps when exact controls matter." },
          { title: "Newsletter or podcast visual", body: "Turn one thoroughly researched idea into a short visual summary that points people back to the fuller episode, article, or source set." },
        ],
      },
      {
        type: "prose",
        heading: "Plan for attention, access, and reuse at the same time",
        body: [
          "The strongest reuse comes from a well-defined core idea, not from cutting a long video into arbitrary fragments. If the main script contains several self-contained decisions, you can create a focused landscape explainer and separate vertical summaries without removing the context that makes them useful. Plan the boundaries before you record narration or build scenes.",
          "Accessibility improves this process rather than slowing it down. Captions help in sound-off feeds, a text summary helps people skim and search, and high-contrast scenes support viewers on smaller screens. Check those essentials before publication, then use the transcript to verify that the visible action and spoken message agree.",
        ],
      },
      {
        type: "faq",
        heading: "Content-creator workflow questions.",
        items: [
          ["How do I make a doodle video feel original?", "Start from your own researched insight, audience question, and script. Use examples to learn pacing and scene structure, not to copy language, claims, or creative work."],
          ["Can I use one project for several platforms?", "A core idea can travel, but frame, pacing, captions, and the opening should respect the context of each channel. Plan the variants before you build the scenes."],
          ["What should I link from a creator video?", "Link to the most useful next resource for the promise you made: a deeper guide, verified source, or related example. Avoid a list of unrelated destinations at the end."],
        ],
      },
      { type: "callout", kind: "editorial", body: "A polished animation cannot compensate for weak research. Keep source notes, review every factual visual, and let the script—not decorative motion—decide what appears on screen." },
    ],
    related: ["/examples", "/resources", "/ai-whiteboard-animation"],
    cta: {
      title: "Turn a researched idea into a scene plan you can reuse.",
      body: "Start with the guide’s planning checklist, then explore the tools that support the workflow you need.",
      primaryHref: "/resources",
      primaryLabel: "Open planning resources",
      secondaryHref: "/doodle-video-creator",
      secondaryLabel: "See the doodle workflow",
    },
  },
  {
    slug: ["examples", "nonprofits"],
    kind: "commercial",
    title: "InstaDoodle Nonprofit Video Examples",
    description: "InstaDoodle nonprofit video examples for explaining a mission, program, or supporter action through clear, accessible whiteboard animation storytelling.",
    h1: "InstaDoodle nonprofit video examples that make the next action clear",
    eyebrow: "Nonprofit examples",
    primaryKeyword: "InstaDoodle nonprofit videos",
    intro: "A nonprofit video can help people understand why a mission matters and what they can do next. This guide uses an official example to explore a respectful, evidence-aware way to turn a program explanation into a clear whiteboard story.",
    heroCtas: [
      { href: "#official-example", label: "Watch the nonprofit example" },
      { href: "/examples", label: "Browse all examples" },
    ],
    blocks: [
      {
        type: "prose",
        heading: "Lead with the human question, then show the path",
        body: [
          "Mission-driven organizations often have a lot to explain: the problem they address, the context behind it, the work they do, the people involved, and the ways supporters can help. A short video cannot carry all of that at once. Start by choosing one human question the viewer can understand, then give the answer enough room to unfold scene by scene.",
          "A respectful narrative avoids turning people or communities into props for a message. Use approved language, evidence, and visuals that reflect the organization’s values. If you cannot substantiate an outcome, do not imply it through dramatic imagery or vague superlatives. Explain the work honestly and direct viewers to the source where program details and current needs are maintained.",
          "Whiteboard animation can be useful for illustrating a process, connection, or decision without requiring a large production. It works especially well for a program overview, an orientation, or a simple action guide. It is not a substitute for the voices and lived experience of people directly involved, so decide when a documentary, interview, or community-approved visual is the more appropriate format.",
        ],
      },
      {
        type: "vimeo",
        anchor: "official-example",
        heading: "Official nonprofit example",
        intro: "Watch the example as a prompt to consider sequence and clarity. Build an original version only from approved facts, language, and calls to action for your organization.",
        video: "nonprofits",
        ctaHref: "/resources",
        ctaLabel: "Use the planning resources",
      },
      {
        type: "cards",
        heading: "Mission-focused video jobs that benefit from clear scenes",
        items: [
          { title: "Program overview", body: "Explain the need, the program approach, and the current next step for someone who is new to the organization. Link to approved reporting or program information." },
          { title: "Volunteer orientation", body: "Show the order of a shift, event, or process so volunteers know what to prepare. Pair the visual with current safety and operational materials." },
          { title: "Supporter action guide", body: "Make one action easy to understand—registering, sharing a resource, attending an event, or checking eligibility—without overstating urgency or impact." },
        ],
      },
      {
        type: "steps",
        heading: "Plan a nonprofit explainer with care",
        intro: "Use a review process that gives accuracy, dignity, and accessibility equal weight with visual polish.",
        items: [
          { title: "Define the audience and their decision", body: "Decide whether the video is for a prospective participant, volunteer, donor, partner, or community member. Each group needs a different opening and a different next action." },
          { title: "Confirm the approved facts", body: "Check program descriptions, eligibility, statistics, names, and images with the people responsible for them. Keep a source note for every claim that could change." },
          { title: "Storyboard the relationship", body: "Use each scene to clarify a relationship: a barrier and support, a request and response, or an action and its immediate next step. Keep people represented with care." },
          { title: "Make access part of production", body: "Provide captions, a readable transcript or summary, high-contrast visual labels, and enough time to process each scene. Test the final action on a phone as well as desktop." },
        ],
      },
      {
        type: "prose",
        heading: "Trust comes from clarity, evidence, and follow-through",
        body: [
          "A mission video earns trust when it tells viewers where information came from and what they can verify next. Instead of filling the last scene with a broad emotional appeal, offer a concrete path: read the current program page, attend an approved event, review eligibility, or contact the official team. That respect for the viewer’s agency is more durable than urgency alone.",
          "Keep the page around the video equally useful. Add an answer-first summary, internal links to the relevant guide or resource, and a short FAQ that reflects genuine questions. Update or retire the video when the program, action, or evidence it describes changes. A clear editorial maintenance process is part of the story you tell.",
        ],
      },
      {
        type: "faq",
        heading: "Nonprofit-video questions.",
        items: [
          ["What should a nonprofit explainer focus on?", "Focus on one audience question and one verified path forward. A video is more useful when it explains a specific program or action than when it tries to summarize an entire mission."],
          ["How can a nonprofit video stay respectful?", "Use approved facts and language, involve appropriate reviewers, avoid stereotypes or unsupported emotional claims, and choose the format that best respects people’s lived experience."],
          ["Should the final CTA ask for a donation?", "Only if giving is the natural, approved next step for the specific message. Other videos may be better served by a resource link, event registration, volunteer information, or a current program page."],
        ],
      },
      { type: "callout", kind: "verify", body: "Do not publish a nonprofit video without the organization’s approval for its facts, program language, imagery, and call to action. Update it when the underlying source information changes." },
    ],
    related: ["/examples", "/resources", "/use-cases"],
    cta: {
      title: "Start with one verified question your audience needs answered.",
      body: "Use the planning resources to map a clear, accessible scene sequence before choosing an animation workflow.",
      primaryHref: "/resources",
      primaryLabel: "Open planning resources",
      secondaryHref: "/whiteboard-animation-examples",
      secondaryLabel: "See example structures",
    },
  },
];
